<a href="https://colab.research.google.com/github/imon333/TensorFLow_Learning/blob/main/00_tensorFlow_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## starting just starting the learning

Introduction to tensorflow

In [1]:
# import TensorFlow
import tensorflow as tf



In [2]:
# Create tensors with tf.constant()

scalar = tf.constant(7)
scalar


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
## Check the number of dimensions of a tensor (ndim = number of dimensions)

scalar.ndim

0

In [4]:
# Crate a vector

vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# check the dimension of out vector

vector.ndim

1

In [6]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10,7],
                    [7,10]])
matrix

matrix.ndim

2

In [7]:
# Create another matrix

another_matrix = tf.constant([[10. , 7.],
                              [3., 2.],
                              [8.,9.]], dtype=tf.float16) # specify the data type dtype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [8]:
# Let's create a tensor
tensor = tf.constant([[[1,2,3,4],
                       [4,5,6,4]],
                      [[7,8,9,4],
                       [10,22,12,4]],
                      [[13,14,15,4],
                       [16,17,18,4]],

                      ])
tensor

<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 4,  5,  6,  4]],

       [[ 7,  8,  9,  4],
        [10, 22, 12,  4]],

       [[13, 14, 15,  4],
        [16, 17, 18,  4]]], dtype=int32)>

In [9]:
tensor.ndim

3

what i've learn so far :
* Scalar: a single number
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers (when n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)  

### Creating tensors with tf.Variables

In [10]:
# Create the same tensor with tf.Variable () as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [11]:
# let's change the changeable tensor with . assign
changeable_tensor[0].assign(69)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([69,  7], dtype=int32)>

In [12]:
# let's change the unchangeable tensor with . assign

#unchangeable_tensor[0].assign(89)


### Random tensors

In [13]:
# Create two random (but the same ) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))

random_2 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_2 = random_2.normal(shape=(3,2))

random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [14]:
# shuffle data in  tensorflow

not_shuffled = tf.constant([[6,9],
                            [3,9],
                            [2,5]])

tf.random.shuffle(not_shuffled,seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 5],
       [3, 9],
       [6, 9]], dtype=int32)>

In [15]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 9],
       [2, 5],
       [6, 9]], dtype=int32)>

## Anotherway __ tensors

In [16]:
# create a tensor of all ones(1)
tf.ones([5,6])

<tf.Tensor: shape=(5, 6), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [17]:
# create a tensor of all zeros(0)
#tf.zeros([5,6])
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

## NumPy into tensors

The main difference between NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU (Much faster for numerical computing)

In [18]:
# numpy array into tensors
import numpy as np

numpy_A = np.arange(1,25, dtype=np.int32)
numpy_A

# X = tf.constant(some_matrix) # capital for matriy or tensor
# y = tf.constant(Vector) # non-capital for vector


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [19]:
A = tf.constant(numpy_A, shape = (3,2,2,2))
B = tf.constant(numpy_A)

A, B

(<tf.Tensor: shape=(3, 2, 2, 2), dtype=int32, numpy=
 array([[[[ 1,  2],
          [ 3,  4]],
 
         [[ 5,  6],
          [ 7,  8]]],
 
 
        [[[ 9, 10],
          [11, 12]],
 
         [[13, 14],
          [15, 16]]],
 
 
        [[[17, 18],
          [19, 20]],
 
         [[21, 22],
          [23, 24]]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [20]:
A.ndim

4

### Getting information for TENSOR
* Shape
* Rank
* Axis or dimension
* Size

In [21]:
# Create a rank 4 tensor (4 dimensions)

rank_4_tensor = tf.zeros(shape = (2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [22]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [23]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

### Indexing tensor
Tensors can be indexed just Python lists.


In [24]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2, :2, : 2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

### Manupulating tensors (tensor operations)

**Basic operation**
+,-,*,/

In [25]:
# You can add valuess to a tensor using the addition operator

tensor = tf.constant([[10,8],[3,4]])
#tensor + 10
#tensor - 10
#tensor * 10
tensor / 10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.8],
       [0.3, 0.4]])>

**Matrix multiplication**

In machine learning, matrix multiplication is one of the most common tensor operations.

In [26]:
# Matrix multiplication tensorflow

print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  8]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[124, 112],
       [ 42,  40]], dtype=int32)>

In [27]:
# Matrix multiplication with python operator "@"

tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[124, 112],
       [ 42,  40]], dtype=int32)>

In [28]:
# Create a tensor 2,3

X = tf.constant([[1,2],
                 [3,4],
                 [5,6],
                 [4,5]])

# Another
Y = tf.constant([[4,2],
                 [5,4],
                 [57,6],
                 [4,95]])



In [29]:
Y=tf.reshape(Y, shape=(2,4)) # reshape of Y

In [30]:
X,Y

(<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6],
        [4, 5]], dtype=int32)>,
 <tf.Tensor: shape=(2, 4), dtype=int32, numpy=
 array([[ 4,  2,  5,  4],
        [57,  6,  4, 95]], dtype=int32)>)

In [31]:
X @ Y

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[118,  14,  13, 194],
       [240,  30,  31, 392],
       [362,  46,  49, 590],
       [301,  38,  40, 491]], dtype=int32)>

In [32]:
# can do the same with transpose
X, tf.transpose(X), tf.reshape(X, shape=(2,4))

(<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6],
        [4, 5]], dtype=int32)>,
 <tf.Tensor: shape=(2, 4), dtype=int32, numpy=
 array([[1, 3, 5, 4],
        [2, 4, 6, 5]], dtype=int32)>,
 <tf.Tensor: shape=(2, 4), dtype=int32, numpy=
 array([[1, 2, 3, 4],
        [5, 6, 4, 5]], dtype=int32)>)

Matrix multiplication with tensors part -3

**The dot product**
Matrix multiplication is also referred to as the dot product.

Matrix mul.. can be perform using :
* 'tf.matmul()'
* 'tf.tensordot()'

In [33]:
X,Y

(<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6],
        [4, 5]], dtype=int32)>,
 <tf.Tensor: shape=(2, 4), dtype=int32, numpy=
 array([[ 4,  2,  5,  4],
        [57,  6,  4, 95]], dtype=int32)>)

In [34]:
# performt the dot product on X and Y (requires X or Y to be tansposed)

tf.tensordot(X,Y, axes = 1)

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[118,  14,  13, 194],
       [240,  30,  31, 392],
       [362,  46,  49, 590],
       [301,  38,  40, 491]], dtype=int32)>

In [35]:
X,Y

(<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6],
        [4, 5]], dtype=int32)>,
 <tf.Tensor: shape=(2, 4), dtype=int32, numpy=
 array([[ 4,  2,  5,  4],
        [57,  6,  4, 95]], dtype=int32)>)

In [36]:
# Perform matrix multiplication between X and Y (trnsposed)

#tf.matmul (X, tf.transpose(Y))

In [37]:
# with reshpae

tf.matmul(X, tf.reshape(Y,shape=(2,4)))

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[118,  14,  13, 194],
       [240,  30,  31, 392],
       [362,  46,  49, 590],
       [301,  38,  40, 491]], dtype=int32)>

In [38]:
# check the value of Y, reshape Y and transposed Y
print("Normal Y:")
print(Y,"\n")

print("Y reshape to (2, 4): ")
print(tf.reshape(Y, (2,4)),"\n")

print("Y transposed:")
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 4  2  5  4]
 [57  6  4 95]], shape=(2, 4), dtype=int32) 

Y reshape to (2, 4): 
tf.Tensor(
[[ 4  2  5  4]
 [57  6  4 95]], shape=(2, 4), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 4 57]
 [ 2  6]
 [ 5  4]
 [ 4 95]], shape=(4, 2), dtype=int32)


### Changing the datatype in Tensor

In [39]:
# Create a new tensor with default datatype (float 32)

B = tf.constant([1,7,7.4])
B.dtype



tf.float32

In [40]:
C = tf.constant([7,10])
C.dtype

tf.int32

In [41]:
# Change from float32 o float16 (reduced precision)

D = tf.cast(B,dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(3,), dtype=float16, numpy=array([1. , 7. , 7.4], dtype=float16)>,
 tf.float16)

In [42]:
# Change from int32 to float32

E = tf.cast(C,dtype=tf.float32)
E,E.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>,
 tf.float32)

### Aggregating tensor

**Basic operations**

In [43]:
tensor = tf.constant([[10,9],[4,5]])
tensor / 10
tensor * 10

## basic +,-,*,/ would be same

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  90],
       [ 40,  50]], dtype=int32)>

## **Matrix Multiplication**
In machine learning, matrix multiplication is one of the most common tensor operations.

In [44]:
# Matrix multiplication in tensorflow
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  9]
 [ 4  5]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[136, 135],
       [ 60,  61]], dtype=int32)>

### Aggregating tensors
Aggregating tensors = condensing them form multiple valuse down to a smaller amount of values.

In [45]:
D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [46]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Let's go through the following forms of aggregation:
+ minimum
+ maximum
+ mean of a tensor
+ sum of a tensor

In [47]:
# Create a random tensor with values betwen 0 and 100 of size 50
F = tf.constant(np.random.randint(1,100, size=50))
F

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([45, 93, 56, 67, 38,  5, 55, 69, 91, 38, 17, 21, 97, 64, 46, 88, 58,
       52, 32, 20, 97, 27, 44, 49, 86, 54, 35, 91, 27, 43, 55, 56, 24, 71,
       14,  8, 69, 25, 56, 20, 66, 10, 41, 30, 15, 23, 75, 75, 92, 83])>

In [48]:
tf.size(F), F.shape, F.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [49]:
# Find the minimum
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=int64, numpy=5>

In [50]:
# Find the max
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=int64, numpy=97>

In [51]:
# Find the mean
tf.reduce_mean(F)

<tf.Tensor: shape=(), dtype=int64, numpy=50>

In [52]:
# Find the sum
tf.reduce_sum(F)

<tf.Tensor: shape=(), dtype=int64, numpy=2513>

## Exercise
need find the variance and standard deviation of F..

In [53]:
F

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([45, 93, 56, 67, 38,  5, 55, 69, 91, 38, 17, 21, 97, 64, 46, 88, 58,
       52, 32, 20, 97, 27, 44, 49, 86, 54, 35, 91, 27, 43, 55, 56, 24, 71,
       14,  8, 69, 25, 56, 20, 66, 10, 41, 30, 15, 23, 75, 75, 92, 83])>

In [54]:
F = tf.cast(F, tf.float64) ## because the math.reduce_variance and std has to be float

variance = tf.math.reduce_variance(F)
std_dev = tf.math.reduce_std(F)

variance, std_dev

(<tf.Tensor: shape=(), dtype=float64, numpy=695.7524000000001>,
 <tf.Tensor: shape=(), dtype=float64, numpy=26.377118872234703>)

## Find positional maximum and minimum

In [55]:
# new transor finding positional max and mini
tf.random.set_seed(40)
x = tf.random.uniform(shape=[50])
x


<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.54513085, 0.7588961 , 0.8362565 , 0.39474642, 0.72001076,
       0.6402768 , 0.15894496, 0.57128036, 0.41122293, 0.18993318,
       0.2312665 , 0.7875649 , 0.18806243, 0.8033031 , 0.12747478,
       0.43258965, 0.98803484, 0.8451586 , 0.9797807 , 0.9952853 ,
       0.6283821 , 0.8643936 , 0.9500631 , 0.41532683, 0.388798  ,
       0.33959448, 0.36432612, 0.79217136, 0.90930283, 0.6459546 ,
       0.4547919 , 0.3669002 , 0.22951639, 0.54661405, 0.9371824 ,
       0.04014015, 0.82825315, 0.45409238, 0.943413  , 0.20978856,
       0.1274836 , 0.9666685 , 0.97015405, 0.568432  , 0.99477863,
       0.39956594, 0.3263564 , 0.61465824, 0.24279046, 0.03102553],
      dtype=float32)>

In [56]:
# positional maxi
tf.argmax(x)

<tf.Tensor: shape=(), dtype=int64, numpy=19>

In [57]:
# index on our largest value position
x[tf.argmax(x)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9952852725982666>

In [58]:
# Find the max value of F

tf.reduce_max(x)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9952852725982666>

In [59]:
# Check for equality
x[tf.argmax(x)] == tf.reduce_max(x)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [60]:
# find min
tf.argmin(x)

<tf.Tensor: shape=(), dtype=int64, numpy=49>

In [61]:
# index on our largest value position
x[tf.argmin(x)]


<tf.Tensor: shape=(), dtype=float32, numpy=0.03102552890777588>

### Squeezing a tensor (removing all single dimension)

In [62]:
# Create a tensor to get started
tf.random.set_seed(42)

G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [63]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [64]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

### One-hot encoding tensor


In [65]:
# Create a list of indices

some_list = [0,1,2,3] # could be red, green , blue, purple

# One hot encode out list indices
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [66]:
# Specify custom values for one hot encoding
tf.one_hot(some_list, depth=4, on_value= "love", off_value="f")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'love', b'f', b'f', b'f'],
       [b'f', b'love', b'f', b'f'],
       [b'f', b'f', b'love', b'f'],
       [b'f', b'f', b'f', b'love']], dtype=object)>

In [67]:
# Create a new tensor

H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [68]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [69]:
# will error method requires non-int type

#Find the squareroot

tf.math.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [70]:
#Find the log here
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

## Tensors and NumPy
TensorFlow interacts beautifully with NumPy arrays.

In [71]:
# Create a tensor directly from a NumPy array
J = tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [72]:
# Convert our tensor back to a NumPy Array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [73]:
# Convert tensor to a NumPy array
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [74]:
J = tf.constant([3.])
J.numpy()[0]

np.float32(3.0)

In [75]:
# Default types of each are slightly different
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3.,4.,9.])

# Check the datatypes of each
numpy_J.dtype,tensor_J.dtype

##---- numpy to tensor,, and direct tensor array might have a different data type


(tf.float64, tf.float32)

#### Finding access to GPUs

In [76]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [77]:
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [79]:
!nvidia-smi

Mon Oct 27 19:10:47 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   55C    P0             27W /   70W |     106MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----