<a href="https://colab.research.google.com/github/imon333/TensorFLow_Learning/blob/main/00_tensorFlow_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## starting just starting the learning

Introduction to tensorflow

In [3]:
# import TensorFlow
import tensorflow as tf



In [4]:
# Create tensors with tf.constant()

scalar = tf.constant(7)
scalar


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
## Check the number of dimensions of a tensor (ndim = number of dimensions)

scalar.ndim

0

In [7]:
# Crate a vector

vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [8]:
# check the dimension of out vector

vector.ndim

1

In [14]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10,7],
                    [7,10]])
matrix

matrix.ndim

2

In [17]:
# Create another matrix

another_matrix = tf.constant([[10. , 7.],
                              [3., 2.],
                              [8.,9.]], dtype=tf.float16) # specify the data type dtype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [25]:
# Let's create a tensor
tensor = tf.constant([[[1,2,3,4],
                       [4,5,6,4]],
                      [[7,8,9,4],
                       [10,22,12,4]],
                      [[13,14,15,4],
                       [16,17,18,4]],

                      ])
tensor

<tf.Tensor: shape=(4, 2, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 4,  5,  6,  4]],

       [[ 7,  8,  9,  4],
        [10, 22, 12,  4]],

       [[13, 14, 15,  4],
        [16, 17, 18,  4]],

       [[13, 14, 15,  4],
        [16, 17, 18,  4]]], dtype=int32)>

In [26]:
tensor.ndim

3

what i've learn so far :
* Scalar: a single number
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers (when n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)  

### Creating tensors with tf.Variables

In [28]:
# Create the same tensor with tf.Variable () as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [32]:
# let's change the changeable tensor with . assign
changeable_tensor[0].assign(69)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([69,  7], dtype=int32)>

In [33]:
# let's change the unchangeable tensor with . assign

unchangeable_tensor[0].assign(89)


AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'