<a href="https://colab.research.google.com/github/imon333/TensorFLow_Learning/blob/main/00_tensorFlow_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## starting just starting the learning

Introduction to tensorflow

In [2]:
# import TensorFlow
import tensorflow as tf



In [3]:
# Create tensors with tf.constant()

scalar = tf.constant(7)
scalar


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
## Check the number of dimensions of a tensor (ndim = number of dimensions)

scalar.ndim

0

In [5]:
# Crate a vector

vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
# check the dimension of out vector

vector.ndim

1

In [7]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10,7],
                    [7,10]])
matrix

matrix.ndim

2

In [8]:
# Create another matrix

another_matrix = tf.constant([[10. , 7.],
                              [3., 2.],
                              [8.,9.]], dtype=tf.float16) # specify the data type dtype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
# Let's create a tensor
tensor = tf.constant([[[1,2,3,4],
                       [4,5,6,4]],
                      [[7,8,9,4],
                       [10,22,12,4]],
                      [[13,14,15,4],
                       [16,17,18,4]],

                      ])
tensor

<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 4,  5,  6,  4]],

       [[ 7,  8,  9,  4],
        [10, 22, 12,  4]],

       [[13, 14, 15,  4],
        [16, 17, 18,  4]]], dtype=int32)>

In [10]:
tensor.ndim

3

what i've learn so far :
* Scalar: a single number
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers (when n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)  

### Creating tensors with tf.Variables

In [11]:
# Create the same tensor with tf.Variable () as above
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [12]:
# let's change the changeable tensor with . assign
changeable_tensor[0].assign(69)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([69,  7], dtype=int32)>

In [13]:
# let's change the unchangeable tensor with . assign

#unchangeable_tensor[0].assign(89)


### Random tensors

In [14]:
# Create two random (but the same ) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))

random_2 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_2 = random_2.normal(shape=(3,2))

random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [15]:
# shuffle data in  tensorflow

not_shuffled = tf.constant([[6,9],
                            [3,9],
                            [2,5]])

tf.random.shuffle(not_shuffled,seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 5],
       [3, 9],
       [6, 9]], dtype=int32)>

In [16]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 9],
       [2, 5],
       [6, 9]], dtype=int32)>

## Anotherway __ tensors

In [17]:
# create a tensor of all ones(1)
tf.ones([5,6])

<tf.Tensor: shape=(5, 6), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [18]:
# create a tensor of all zeros(0)
#tf.zeros([5,6])
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

## NumPy into tensors

The main difference between NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU (Much faster for numerical computing)

In [19]:
# numpy array into tensors
import numpy as np

numpy_A = np.arange(1,25, dtype=np.int32)
numpy_A

# X = tf.constant(some_matrix) # capital for matriy or tensor
# y = tf.constant(Vector) # non-capital for vector


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [20]:
A = tf.constant(numpy_A, shape = (3,2,2,2))
B = tf.constant(numpy_A)

A, B

(<tf.Tensor: shape=(3, 2, 2, 2), dtype=int32, numpy=
 array([[[[ 1,  2],
          [ 3,  4]],
 
         [[ 5,  6],
          [ 7,  8]]],
 
 
        [[[ 9, 10],
          [11, 12]],
 
         [[13, 14],
          [15, 16]]],
 
 
        [[[17, 18],
          [19, 20]],
 
         [[21, 22],
          [23, 24]]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [21]:
A.ndim

4

### Getting information for TENSOR
* Shape
* Rank
* Axis or dimension
* Size

In [22]:
# Create a rank 4 tensor (4 dimensions)

rank_4_tensor = tf.zeros(shape = (2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [23]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [24]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

### Indexing tensor
Tensors can be indexed just Python lists.


In [25]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2, :2, : 2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

### Manupulating tensors (tensor operations)

**Basic operation**
+,-,*,/

In [26]:
# You can add valuess to a tensor using the addition operator

tensor = tf.constant([[10,8],[3,4]])
#tensor + 10
#tensor - 10
#tensor * 10
tensor / 10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.8],
       [0.3, 0.4]])>

**Matrix multiplication**

In machine learning, matrix multiplication is one of the most common tensor operations.

In [27]:
# Matrix multiplication tensorflow

print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  8]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[124, 112],
       [ 42,  40]], dtype=int32)>

In [28]:
# Matrix multiplication with python operator "@"

tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[124, 112],
       [ 42,  40]], dtype=int32)>

In [29]:
# Create a tensor 2,3

X = tf.constant([[1,2],
                 [3,4],
                 [5,6],
                 [4,5]])

# Another
Y = tf.constant([[4,2],
                 [5,4],
                 [57,6],
                 [4,95]])



In [30]:
Y=tf.reshape(Y, shape=(2,4)) # reshape of Y

In [31]:
X,Y

(<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6],
        [4, 5]], dtype=int32)>,
 <tf.Tensor: shape=(2, 4), dtype=int32, numpy=
 array([[ 4,  2,  5,  4],
        [57,  6,  4, 95]], dtype=int32)>)

In [32]:
X @ Y

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[118,  14,  13, 194],
       [240,  30,  31, 392],
       [362,  46,  49, 590],
       [301,  38,  40, 491]], dtype=int32)>

In [38]:
# can do the same with transpose
X, tf.transpose(X), tf.reshape(X, shape=(2,4))

(<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6],
        [4, 5]], dtype=int32)>,
 <tf.Tensor: shape=(2, 4), dtype=int32, numpy=
 array([[1, 3, 5, 4],
        [2, 4, 6, 5]], dtype=int32)>,
 <tf.Tensor: shape=(2, 4), dtype=int32, numpy=
 array([[1, 2, 3, 4],
        [5, 6, 4, 5]], dtype=int32)>)